services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\SentryAsync\:
    resource: '../src/*'

  AUS\SentryAsync\Transport\QueueTransport:
    public: true

  AUS\SentryAsync\Command\FlushCommand:
    tags:
      - name: 'console.command'
        command: 'andersundsehr:sentry-async:flush'
        description: 'Transports potentially queued sentry events'
