services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\SentryAsync\Queue\:
    resource: '../src/Queue/*'

  AUS\SentryAsync\Transport\TransportFactory:
    public: true


  AUS\SentryAsync\Transport\QueueTransport:
    arguments:
      $options: '@sentry.client.options'

  Sentry\Serializer\PayloadSerializer:
    public: true

  Sentry\Serializer\PayloadSerializerInterface:
    alias: Sentry\Serializer\PayloadSerializer
    public: true


  AUS\SentryAsync\Queue\QueueInterface:
    alias: AUS\SentryAsync\Queue\FileQueue
    public: true


  AUS\SentryAsync\Command\FlushCommand:
    tags:
      - name: 'console.command'
        command: 'andersundsehr:sentry-async:flush'
        description: 'Transports potentially queued events'
